# Generated by Django 5.0.6 on 2024-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasrequest',
            name='image',
            field=models.ImageField(upload_to='ImageReq'),
        ),
    ]
